# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: atueda
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-stat
service: aws-stat
provider:
  name: aws
  runtime: nodejs20.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline